Fix #1 - https://tour.golang.org/basics/4-16
pondok-programmer/golang-learn pull request #35
Opened 2020-02-06 10:30 UTC by Syarif1922

2020-02-06 10:42 UTC, muizidn requested changes
Ada beberapa yang perlu dirubah.

`fmt.Printf` bukan `fmt.Println`
dan
logic swap

2020-02-06 10:42 UTC, muizidn commented on syarif/basics6.go
> +	return a, b
seharusnya `return b, a`. Kalau masih `a, b` tidak akan ditukar _swap_

2020-02-06 10:42 UTC, muizidn commented on syarif/basics12.go
> +	fmt.Println("%v %v %v %q\n", i, f, b, s)
seharusnya `fmt.Printf` bukan `fmt.Println`

2020-02-06 10:42 UTC, muizidn commented on syarif/basics11.go
> +	fmt.Println("Type: %T Value: %v\n", z, z)
seharusnya `fmt.Printf` bukan `fmt.Println`

2020-02-06 10:43 UTC, muizidn commented
Untuk komentar commit jadi `Fix #35 - blablabla`

2020-02-07 02:36 UTC, Syarif1922 commented on syarif/basics6.go
> +	return a, b
ini sudah ane perbaiki

2020-02-07 02:36 UTC, Syarif1922 commented on syarif/basics12.go
> +	fmt.Println("%v %v %v %q\n", i, f, b, s)
sudah

2020-02-07 02:37 UTC, Syarif1922 commented on syarif/basics11.go
> +	fmt.Println("Type: %T Value: %v\n", z, z)
juga sudah bang

2020-02-10 13:16 UTC, muizidn approved these changes

2020-02-10 13:17 UTC, merged

2020-02-12 00:23 UTC, muizidn commented
Ah, lupa, haruse commit mu jadi #28 pak

2020-02-12 00:24 UTC, muizidn commented
Tapi next time lah.